name: Release
on: 
  push:
    tags: 
      - 'v*'

jobs:
  build_artifacts:
    name: Build artifacts for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/direnv-pretty-linux
            asset_name: direnv-pretty-linux
          - name: macos
            os: macos-latest
            artifact_name: target/release/direnv-pretty-macos
            asset_name: direnv-pretty-macos

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --release --locked

      - name: Rename artifacts
        run: mv target/release/direnv-pretty target/release/${{ matrix.asset_name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}

  build_artifacts_m1:
    name: Build artifacts for macos M1
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: aarch64-apple-darwin

      - name: Build
        run: cargo build --release --locked --target aarch64-apple-darwin

      - name: Rename artifacts
        run: mv target/aarch64-apple-darwin/release/direnv-pretty target/release/direnv-pretty-macos-m1

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: direnv-pretty-macos-m1
          path: target/release/direnv-pretty-macos-m1

  deploy_artifacts:
    name: Create release
    needs: [build_artifacts, build_artifacts_m1]
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v3.0.0

      - run: ls

      - name: Upload release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "direnv-pretty-*/*"
          token: ${{ secrets.GITHUB_TOKEN }}
